name: settings_builder_test
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  meta: ^1.7.0
  mocktail: ^0.2.0
  settings_annotation: ^1.0.0
  settings_builder: ^1.0.0
  test: ^1.20.1
  tuple: ^2.0.0

dependency_overrides:
  settings_annotation:
    path: ../settings_annotation
  settings_builder:
    path: ../settings_builder
