builders:
  settings_builder:
    import: "package:settings_builder/builder.dart"
    builder_factories: ["settingsBuilder"]
    build_extensions: { ".dart": ["settings.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
