name: settings_annotation
description: Annotations for the settings_builder package.
version: 1.0.1
homepage: https://github.com/Skycoder42/settings_builder/tree/main/packages/settings_annotation

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.10.0

dev_dependencies:
  cider: ^0.2.4
  custom_lint: ^0.5.7
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.0

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - meta

cider:
  link_template:
    tag: https://github.com/Skycoder42/settings_builder/releases/tag/settings_annotation-v%tag%
    diff: https://github.com/Skycoder42/settings_builder/compare/settings_annotation-v%from%...settings_annotation-v%to%
