builders:
  settings_builder:
    import: "package:settings_builder/settings_builder.dart"
    builder_factories: ["settingsBuilder"]
    build_extensions: { ".dart": ["settings.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      settings_builder:
        enabled: true
        generate_for:
          exclude:
            - lib
            - test
          include:
            - test/models/**
            - example/**
