name: settings_builder
description: A dart builder that generates automatic accessors for reading and writing shared preferences.
version: 1.1.0
homepage: https://github.com/Skycoder42/settings_builder/tree/main/packages/settings_builder

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  analyzer: ^2.8.0
  build: ^2.2.1
  build_config: ^1.0.0
  code_builder: ^4.1.0
  meta: ^1.7.0
  settings_annotation: ^1.0.0
  source_gen: ^1.2.1
  source_helper: ^1.3.1

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  lint: ^1.8.2
  mocktail: ^0.2.0
  source_gen_test: ^1.0.2
  test: ^1.20.1
  tuple: ^2.0.0

dependency_overrides:
  settings_annotation:
    path: ../settings_annotation
