name: settings_builder
description: A dart builder that generates automatic accessors for reading and writing shared preferences.
version: 1.1.1
homepage: https://github.com/Skycoder42/settings_builder/tree/main/packages/settings_builder

environment:
  sdk: ^3.2.0

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.9.0
  meta: ^1.10.0
  settings_annotation: ^1.0.1
  source_gen: ^1.5.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.2
  cider: ^0.2.4
  custom_lint: ^0.5.7
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.0
  mocktail: ^1.0.2
  source_gen_test: ^1.0.6
  test: ^1.25.0

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - analyzer
      - meta

cider:
  link_template:
    tag: https://github.com/Skycoder42/settings_builder/releases/tag/settings_builder-v%tag%
    diff: https://github.com/Skycoder42/settings_builder/compare/settings_builder-v%from%...settings_builder-v%to%
