name: CI/CD for settings_builder

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/settings_builder/**"
      - ".github/workflows/settings_builder_*.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/settings_builder
      removePubspecOverrides: false
      buildRunner: true
      minCoverage: 0
  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    with:
      workingDirectory: packages/settings_builder
      buildRunner: true
      tagPrefix: settings_builder-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
