name: CI/CD for settings_builder

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/settings_builder/**"
      - ".github/workflows/settings_builder.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/settings_builder/**"
      - ".github/workflows/settings_builder.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/settings_builder
      buildRunner: true
      minCoverage: 0
  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    with:
      workingDirectory: packages/settings_builder
      buildRunner: true
    secrets:
      PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
