name: CI/CD for settings_annotation

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/settings_annotation/**"
      - ".github/workflows/settings_annotation_*.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/settings_annotation
      buildRunner: false
      unitTestPaths: ""
      minCoverage: 0
      panaScoreThreshold: 10
  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    with:
      workingDirectory: packages/settings_annotation
      tagPrefix: settings_annotation-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
